Repository go-resty/resty, pull requests merged in 2021-09, with the labels that each got.

#453 Version update 2.6.0 on readme for go.mod
  README.md
Labels: documentation

#434 Add 1.16.x and remove 1.14.x from the travis build
  .travis.yml
Labels: enhancement, test case

#452 feat(#432): Implement Easier Adding of Multiple Value HTTP Header
  request.go
  request_test.go
Labels: enhancement, v2

#421 Don't use sync.Pool for json.NewEncoder target buffers
  client.go
  middleware.go
  request.go
  util.go
Labels: enhancement, v2

#438 Handle EOF from multipart form file readers
  util.go
  util_test.go
Labels: bug, v2

#436 Added RetryConditions to Request
  client.go
  request.go
Labels: enhancement, v2

#460 Addressing SetScheme option side effects on schemeless Host URL #407
  .travis.yml
  client.go
  client_test.go
  middleware.go
  request_test.go
Labels: bug, v2
