Repository go-resty/resty, pull requests merged in 2021-01, with the labels that each got.

#388 retry.go: Fix sleep computation for 32bit arch
  retry.go
Labels: bug

#403 Enhancements
  client.go
  middleware.go
  request.go
  request_test.go
Labels: enhancement

#385 For v2.4.0 release
  README.md
  go.mod
  go.sum
  resty.go
Labels: v2
