Repository go-resty/resty, pull requests merged in 2023-09, with the labels that each got.

#692 Revert and fix pr 541
  .github/workflows/ci.yml
  client_test.go
  middleware.go
Labels: bug

#691 Enhance retry behavior documentation in README.md
  README.md
Labels: documentation

#685 fix: through typo
  README.md
Labels: documentation

#664 Support RawPathParams without escaping
  client.go
  middleware.go
  request.go
  request_test.go
Labels: enhancement, run-build

#662 CVE-2021-43565 CVE-2022-27191 fix
  go.mod
  go.sum
Labels: enhancement, run-build

#645 update README.md about Proxy Settings, no Request level setting
  README.md
Labels: documentation

#587 Update log level to warning for errors within retry block
  request.go
Labels: enhancement, run-build

#654 Improve 204 no content handling
  middleware.go
  response.go
Labels: enhancement, run-build

#683 improve: support js,wasm
  transport.go
  transport_js.go
  transport_other.go
Labels: enhancement, run-build

#693 For v2.8.0 release
  .github/workflows/ci.yml
  .github/workflows/label-actions.yml
  README.md
  client.go
  client_test.go
  middleware.go
  redirect.go
  request.go
  request_test.go
  resty.go
Labels: enhancement

#694 config: update golang.org/x/net dependency to latest v0.15.0
  go.mod
  go.sum
Labels: enhancement

#674 fix: parseResponseBody overrides original error code in case of unmar…
  middleware.go
  request_test.go
  resty_test.go
Labels: enhancement

#698 Set ContentLength to 0 when Body is nil
  client_test.go
  middleware.go
Labels: bug

#702 fix: improve regex expression for json and xml content type validation
  client.go
  util_test.go
Labels: bug

#703 test: add test example for unix socket client and update readme #589
  README.md
  client_test.go
  resty_test.go
Labels: documentation, test case

#704 test: added validation test case, unable to reproduce #524
  request_test.go
Labels: test case

#705 fix: correct url path params processing order #519
  middleware.go
Labels: bug

#706 refactor: inherit value from client enables clean request overrides #516
  client.go
  middleware.go
Labels: enhancement

#707 fix: add missing source files in the bazel build config #700
  BUILD.bazel
Labels: bug

#709 unit tests for parseRequestURL function
  middleware.go
  middleware_test.go
Labels: test case

#715 Add rate limiter to client
  client.go
  go.mod
  go.sum
  request_test.go
  util.go
Labels: feature
