Repository go-resty/resty, pull requests merged in 2023-10, with the labels that each got.

#716 chore: readme, docs, and version update
  README.md
  client.go
  resty.go
Labels: documentation

#714 Add Benchmarks and Unit tests for parseRequestBody and improve it
  middleware.go
  middleware_test.go
Labels: optimization

#711 Benchmarks and Improvements for parseRequestURL function
  middleware.go
  middleware_test.go
Labels: optimization

#724 feat(enhancement): add SetBody method in Response struct #721
  request_test.go
  response.go
  retry_test.go
Labels: enhancement

#726 chore: prep commit for v3.0.0 development
  example_test.go
  go.mod
  go.sum
  resty.go
Labels: run-build

#727 fix: request debug log loss cookie header when cookiejar in use #424
  .github/workflows/ci.yml
  go.mod
  go.sum
  middleware.go
  util.go
Labels: bug

#730 Fix digest auth http: ContentLength=xxx with Body length 0
  digest.go
  request_test.go
Labels: bug

#731 chore: update go mod dependency
  go.mod
  go.sum
Labels: enhancement

#732 release: v2.10.0 updates
  README.md
  resty.go
Labels: documentation
