Repository go-resty/resty, pull requests merged in 2023-12, with the labels that each got.

#745 Security: Don't put the same bytes.Buffer into sync.Pool twice
  middleware.go
Labels: bug, run-build

#735 fix: Improve Digest WWW-Authenticate response header parsing compatibility
  digest.go
Labels: bug, enhancement

#767 release: v2.11.0 update
  README.md
Labels: documentation
