Repository go-resty/resty, pull requests merged in 2023-03, with the labels that each got.

#582 feat: add nil check to SetResult (#503)
  request.go
  request_test.go
Labels: enhancement

#584 feat: add SetLogger() method on Request
  client.go
  middleware.go
  request.go
  request_test.go
  resty_test.go
Labels: feature

#586 add OnSuccess, OnPanic, and OnInvalid hooks
  client.go
  client_test.go
  context_test.go
  request.go
  request_test.go
Labels: enhancement

#627 Prep work v2.8.0
  .github/workflows/ci.yml
  client_test.go
  go.mod
  go.sum
  transport.go
  transport112.go
Labels: enhancement

#583 Add digest authentication
  client.go
  client_test.go
  digest.go
  request.go
  request_test.go
  resty_test.go
Labels: feature

#628 Add go fmt to github actions
  .github/workflows/ci.yml
Labels: code-quality

#629 fix: jitter maxWaitTime must be >= 1ns
  retry.go
  retry_test.go
Labels: bug

#633 fix: client panic on missing digest value
  client_test.go
  digest.go
  resty_test.go
Labels: bug

#635 fix sync pool data race: deep copy
  middleware.go
Labels: bug

#605 feat: Export transport method to return current transport from the client
  client.go
  client_test.go
  request_test.go
Labels: enhancement

#637 feat: export NoRedirectPolicy error
  redirect.go
Labels: enhancement
