Repository go-resty/resty, pull requests merged in 2024-12, with the labels that each got.

#923 feat: enable resty's vanity package url
  client_test.go
  example_test.go
  go.mod
  resty.go
Labels: feature, v3

#924 feat(enhancement): remove unnecessary map for raw path params instead use path params
  .github/workflows/ci.yml
  .github/workflows/label-actions.yml
  benchmark_test.go
  client.go
  client_test.go
  curl_test.go
  digest.go
  digest_test.go
  go.mod
  go.sum
  middleware.go
  middleware_test.go
  multipart_test.go
  request.go
  request_test.go
  response.go
  resty.go
  resty_test.go
  stream.go
Labels: enhancement

#931 feat: add server-sent events client #658
  client.go
  resty_test.go
  retry.go
  sse.go
  sse_test.go
Labels: feature, v3

#932 feat: auto parse filename from content-disposition or URL #926
  client.go
  middleware.go
  middleware_test.go
  request.go
  request_test.go
  resty_test.go
  util.go
Labels: feature, breaking change, v3

#933 feat: add redirect history feature #295
  client_test.go
  redirect.go
  request_test.go
  response.go
Labels: feature, v3

#930 feat: Client Circuit Breaker
  circuit_breaker.go
  client.go
  client_test.go
Labels: feature, v3
