Repository go-resty/resty, pull requests merged in 2024-09, with the labels that each got.

#838 feat(enhancement): add ability to override default value and provide transport settings on resty client #814
  client.go
  client_test.go
  resty.go
Labels: enhancement, v3

#840 feat(enhancement): inherit client values in the request during a creation and use it afterwards #796
  .github/workflows/ci.yml
  .github/workflows/label-actions.yml
  client.go
  client_test.go
  go.mod
  middleware.go
  middleware_test.go
  request.go
  request_test.go
  response.go
  util.go
Labels: enhancement

#841 Update go vesion to 1.20
  .github/workflows/ci.yml
  .github/workflows/label-actions.yml
  go.mod
Labels: build

#836 Fix request/response logging for SetDoNotParseResponse(true)
  client.go
  client_test.go
  context_test.go
Labels: bug, enhancement

#842 fix(enhancement): add explicit option to enable generate curl command in conjunction with debug mode and few clean ups #828
  client.go
  curl_cmd_test.go
  examples/BUILD.bazel
  examples/server_test.go
  middleware.go
  request.go
  resty_test.go
  util_curl.go
Labels: bug, enhancement

#845 fix: add missing middleware for generating curl command
  resty.go
Labels: bug

#848 feat(refactor): for pr #826
  client.go
Labels: optimization

#849 doc: godoc improvements and corrections
  client.go
  redirect.go
  request.go
  response.go
  resty.go
  retry.go
  shellescape/shellescape.go
  trace.go
  util.go
Labels: documentation

#847 feat: add `Clone` method for Request
  client_test.go
  request.go
  request_test.go
  util.go
  util_test.go
Labels: feature, v3

#851 doc: godoc improvements
  client.go
  redirect.go
  request.go
  response.go
  resty.go
  retry.go
  shellescape/shellescape.go
  trace.go
Labels: documentation

#852 release: version bump and readme update for v2.15.0
  README.md
  resty.go
Labels: v2

#854 Cleanup and improvements
  client.go
  client_test.go
  example_test.go
  middleware.go
  middleware_test.go
  request.go
  request_test.go
  response.go
  resty.go
  resty_test.go
  retry_test.go
  util.go
Labels: enhancement, feature, breaking change, v3

#855 feat: add retry settings method at request level #752
  client.go
  request.go
  retry_test.go
Labels: feature, v3

#858 fix: do not parse response debug log with correct text
  request_test.go
  response.go
Labels: bug

#857 feat!: add content type encoder and decoder, implement decoder for response consumption #439
  client.go
  client_test.go
  context_test.go
  middleware.go
  request.go
  request_test.go
  response.go
  resty.go
  resty_test.go
  retry_test.go
  stream.go
  util.go
Labels: breaking change, v3

#862 feat(continue)!: add content type encoder and decoder, implement encoder in the request generation flow #439
  client.go
  middleware.go
  middleware_test.go
  request.go
  request_test.go
  resty_test.go
  stream.go
  util.go
  util_curl.go
Labels: v3

#872 fix: 'invalid memory address or nil pointer dereference' in response logger
  middleware.go
Labels: bug

#875 feat: add context concept into client and update request flow with features #722
  client.go
  client_test.go
  context_test.go
  middleware.go
  request.go
  request_test.go
  resty_test.go
  util.go
Labels: feature
