Repository go-resty/resty, pull requests merged in 2024-02, with the labels that each got.

#769 fix: doc typo
  middleware.go
Labels: run-build

#772 docs: replace `SetHostURL` to `SetBaseURL`
  README.md
Labels: documentation

#775 Fixed JSON request logging data race.
  client_test.go
  request.go
Labels: bug
