Repository go-resty/resty, pull requests merged in 2024-10, with the labels that each got.

#876 feat: add way to set empty header on request #496
  middleware.go
  request.go
Labels: feature

#879 feat: add multipart file upload streaming #309
  client.go
  client_test.go
  middleware.go
  middleware_test.go
  multipart.go
  multipart_test.go
  request.go
  request_test.go
  resty_test.go
  retry.go
  util.go
  util_test.go
Labels: feature, v3

#880 feat: add multipart live upload progress callback #287, #379
  middleware.go
  multipart.go
  multipart_test.go
  request.go
Labels: feature

#882 Remove setcontentlength from reader flow
  middleware.go
  middleware_test.go
Labels: enhancement, breaking change, v3

#883 feat!: disallow the DELETE verb payload by default and provide the option to allow it #881
  client.go
  client_test.go
  middleware.go
  middleware_test.go
  request.go
  request_test.go
  resty_test.go
  util.go
Labels: feature, breaking change

#884 Enhance buildCurlRequest for unit test
  curl_cmd_test.go
  util_curl.go
Labels: enhancement, hacktoberfest-accepted

#885 feat: option to set URL query params without encoding
  client.go
  middleware.go
  middleware_test.go
  request.go
  resty_test.go
Labels: feature

#889 feat!: add load balancer with couple of algorithms OOTB, lb interface is extensible #430 #274
  README.md
  client.go
  load_balancer.go
  load_balancer_test.go
  middleware.go
  middleware_test.go
  request.go
  request_test.go
Labels: feature, breaking change

#866 feat: Implement ability to dynamically reload Root & Client Root TLS certificates
  cert_watcher_test.go
  client.go
  client_test.go
  resty.go
Labels: feature

#894 feat!: redesign request retry flow, retry-after header, default retry conditions #886
  README.md
  client.go
  client_test.go
  context_test.go
  middleware.go
  request.go
  request_test.go
  resty.go
  resty_test.go
  retry.go
  retry_test.go
  util.go
  util_test.go
Labels: feature, breaking change

#895 feat: retry only idempotent methods #777
  multipart_test.go
  request.go
  request_test.go
  resty_test.go
  retry_test.go
Labels: breaking change, v3

#896 fix: unnecessary request cycle on non-idempotent methods #777
  request.go
  request_test.go
Labels: bug, v3
